---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/tekton.dev/task_v1.json
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lychee
  namespace: tekton-pipelines
spec:
  description: >-
    Check all markdown files for links and verify that they are still valid using lychee.
  params:
    - name: token
      description: GitHub access token
    - name: exclude-links
      description: Exclude specific URLs, space separated list
    - name: exclude-paths
      description: Exclude specific paths, space separated list
  workspaces:
    - name: repo
      description: Workspace containgin the repository to scan
      mountPath: /workspaces/repo
  results:
    - name: summary
      description: The generated summary of the scan result
  steps:
    - name: lychee
      image: docker.io/lycheeverse/lychee:0.24.2
      env:
        - name: GITHUB_TOKEN
          value: $(params.token)
        - name: EXCLUDE_LINKS
          value: $(params.exclude-links)
        - name: EXCLUDE_PATHS
          value: $(params.exclude-paths)
        - name: OUTPUT_PATH
          value: $(results.summary.path)
        - name: REPO_PATH
          value: $(workspaces.repo.path)
      script: |
        #!/bin/bash

        set -ex

        cd "${REPO_PATH}"

        IFS=' ' read -r -a excluded_urls <<< "${EXCLUDE_LINKS}"
        IFS=' ' read -r -a excluded_paths <<< "${EXCLUDE_PATHS}"
        urls=""
        paths=""
        for url in "${excluded_urls[@]}"; do
            if [ -n "${url}" ]; then
                urls="${urls} --exclude ${url}"
            fi
        done
        for path in "${excluded_paths[@]}"; do
            if [ -n "${path}" ]; then
                paths="${paths} --exclude-path ${path}"
            fi
        done

        lychee --format markdown --output "${OUTPUT_PATH}" --verbose --no-progress ${urls} ${paths} './**/*.md'
---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/tekton.dev/task_v1.json
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: gh-issue
  namespace: tekton-pipelines
spec:
  description: >-
    Update the Issue with the given title and the specified body.
    If no issue with the exact title is found, a new one is created.
  params:
    - name: token
      description: GitHub access token
    - name: repo
      description: Name of the GitHub repository
    - name: title
      description: Title of the issue
    - name: body
      description: Body of the issue
  steps:
    - name: issue
      image: ghcr.io/heathcliff26/gh-utility:v0.0.3@sha256:7fc5f6c7dd06ab13441e887a830d38bbe0a8b2115c9193082749a1c9ba2ddb6c
      env:
        - name: GITHUB_TOKEN
          value: $(params.token)
        - name: GITHUB_REPO
          value: $(params.repo)
        - name: ISSUE_TITLE
          value: $(params.title)
        - name: ISSUE_BODY
          value: $(params.body)
      script: |
        #!/bin/sh

        set -ex

        export GITHUB_REPO="heathcliff26/${GITHUB_REPO}"

        issue_number=$( \
                      gh issue list \
                        --repo "${GITHUB_REPO}" \
                        --search "in:title ${ISSUE_TITLE}" \
                        --state open \
                        --json number \
                      | jq --raw-output '.[0].number' \
                  )

        if [ "${issue_number}" = "null" ] || [ "${issue_number}" = "" ]; then
          echo "Creating new issue"
          gh issue create \
            --repo "${GITHUB_REPO}" \
            --title "${ISSUE_TITLE}" \
            --body "${ISSUE_BODY}"
        else
          echo "Updating issue ${issue_number}"
          gh issue edit "${issue_number}" \
            --repo "${GITHUB_REPO}" \
            --title "${ISSUE_TITLE}" \
            --body "${ISSUE_BODY}"
        fi
