---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/triggers.tekton.dev/triggerbinding_v1beta1.json
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: link-check-cron
  namespace: tekton-ci
spec:
  params:
    - name: repo
      value: $(body.repo)
    - name: exclude-links
      value: $(body.exclude-links)
    - name: exclude-paths
      value: $(body.exclude-paths)
---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/triggers.tekton.dev/triggertemplate_v1beta1.json
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: link-check-cron
  namespace: tekton-ci
spec:
  params:
    - name: repo
      description: The github repository to update.
    - name: exclude-links
      description: Exclude specific URLs
      default: ""
    - name: exclude-paths
      description: Exclude specific paths
      default: ""
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: link-check-$(tt.params.repo)-
        namespace: tekton-ci
        labels:
          pipeline: link-check
          repo: $(tt.params.repo)
      spec:
        pipelineRef:
          name: link-check
        params:
          - name: repo
            value: $(tt.params.repo)
          - name: exclude-links
            value: $(tt.params.exclude-links)
          - name: exclude-paths
            value: $(tt.params.exclude-paths)
        workspaces:
          - name: repo
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: p3-tmp

