---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pipeline.yaml
  - pvc.yaml
  - tasks.yaml
  - trigger.yaml
configMapGenerator:
  - name: renovate-bot-config
    namespace: tekton-ci
    files:
      - renovate-bot.json5
    options:
      disableNameSuffixHash: true
