---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/tekton.dev/pipeline_v1.json
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: renovate
  namespace: tekton-pipelines
spec:
  description: |
    Run renovate on the given repository
  params:
    - name: repo
      type: string
      description: The github repository to update.
    - name: dry-run
      type: string
      description: dry-run
      default: "null"
    - name: log-level
      type: string
      description: Set log-level
      default: debug
    - name: cache
      type: string
      description: Persist renovate cache between runs
      default: true
  tasks:
    - name: token
      retries: 0
      taskRef:
        name: token
    - name: renovate
      retries: 0
      taskRef:
        name: renovate
      params:
        - name: token
          value: $(tasks.token.results.token)
        - name: repo
          value: $(params.repo)
        - name: dry-run
          value: $(params.dry-run)
        - name: log-level
          value: $(params.log-level)
        - name: cache
          value: $(params.cache)
