---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: p3-hdd-ephemeral
  resources:
    requests:
      storage: 10Gi
