---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
  namespace: tekton-ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: p3-tmp
  resources:
    requests:
      storage: 10Gi
