---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: predictable-path-provisioner-link-check
  namespace: tekton-ci
spec:
  schedule: "15 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: quay.io/curl/curl:8.20.0
            args: ["curl", "-X", "POST", "--data", '{"pipeline": "link-check", "repo": "predictable-path-provisioner", "exclude-paths": "vendor"}', "el-cron.tekton-ci.svc.cluster.local:8080"]
          restartPolicy: Never
