---
group:
  - repos: |
      heathcliff26/infraspace-savegame-editor@main
      heathcliff26/containers@main
      heathcliff26/promremote@main
      heathcliff26/cloudflare-dyndns@main
      heathcliff26/minecraft-exporter@main
      heathcliff26/simple-fileserver@main
      heathcliff26/speedtest-exporter@main
      heathcliff26/wsl2-ssh-pageant@main
      heathcliff26/go-minesweeper@main
      heathcliff26/fleetlock@main
      heathcliff26/kube-upgrade@main
      heathcliff26/go-wol@main
    files:
      - source: .github/renovate-bot.json5
        dest: .github/renovate-bot.json5
      - source: .editorconfig
        dest: .editorconfig
      - source: .vscode/extensions.json
        dest: .vscode/extensions.json

  - repos: |
      heathcliff26/infra@main
    files:
      - source: .github/renovate-bot.json5
        dest: .github/renovate-bot.json5
      - source: .vscode/extensions.json
        dest: .vscode/extensions.json

  - repos: |
      heathcliff26/promremote@main
      heathcliff26/cloudflare-dyndns@main
      heathcliff26/minecraft-exporter@main
      heathcliff26/simple-fileserver@main
      heathcliff26/speedtest-exporter@main
      heathcliff26/fleetlock@main
      heathcliff26/kube-upgrade@main
      heathcliff26/go-wol@main
    files:
      - source: renovate/configs/golang.json5
        dest: .github/renovate.json5
      - source: .golangci.yml
        dest: .golangci.yml

  - repos: |
      heathcliff26/go-minesweeper@main
      heathcliff26/infraspace-savegame-editor@main
    files:
      - source: .golangci.yml
        dest: .golangci.yml
