---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: godialog-link-check
  namespace: tekton-ci
spec:
  schedule: "10 0 * * 0"
  timeZone: "Europe/Berlin"
  jobTemplate:
    spec:
      # Delete the job after 3 days to free up resources.
      ttlSecondsAfterFinished: 259200
      template:
        spec:
          containers:
          - name: curl
            image: quay.io/curl/curl:8.21.0
            args: ["curl", "-X", "POST", "--data", '{"pipeline": "link-check", "repo": "godialog"}', "el-cron.tekton-ci.svc.cluster.local:8080"]
          restartPolicy: Never
