---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/tekton.dev/task_v1.json
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pr
  namespace: tekton-ci
spec:
  description: >-
    Commit the current changes and open a pull request.
    Will force push to the given branch.
  params:
    - name: token
      description: GitHub access token
    - name: directory
      description: Directory relative to the workspace root
      default: "."
    - name: branch
      description: Branch name for the pull request.
    - name: title
      description: PR Title
    - name: body
      description: PR Body
      default: ""
    - name: labels
      description: Comma separated list of labels to apply to the PR
      default: ""
  workspaces:
    - name: repo
      description: Workspace containing the repository into
      mountPath: /workspaces/repo
  steps:
    - name: pr
      image: ghcr.io/heathcliff26/gh-utility:v0.0.7@sha256:d06e7103a4c69e2f6423b09ad35bb442de4df491713dcf4e22a02d68b0beb7f8
      timeout: 5m
      env:
        - name: GITHUB_TOKEN
          value: $(params.token)
        - name: WORKDIR
          value: $(workspaces.repo.path)/$(params.directory)
        - name: PR_BRANCH
          value: $(params.branch)
        - name: PR_TITLE
          value: $(params.title)
        - name: PR_BODY
          value: $(params.body)
        - name: PR_LABELS
          value: $(params.labels)
      script: |
        #!/bin/sh

        set -ex

        cd "${WORKDIR}"

        label_flags=""
        # shellcheck disable=SC3060
        for label in ${PR_LABELS//,/ }; do
            label_flags="${label_flags} --label ${label}"
        done

        gh-utility pr --branch "${PR_BRANCH}" --title "${PR_TITLE}" --body "${PR_BODY}" ${label_flags}
