---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/tekton.dev/task_v1.json
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: token
  namespace: tekton-ci
spec:
  description: >-
    Create a temporary access token for the GitHub App.
  results:
    - name: token
      description: The generated app token
  steps:
    - name: get-token
      image: ghcr.io/heathcliff26/gh-utility:v0.0.5@sha256:fa925454cffbc52c5c198bfb14fc9f842338e658fa7c4a0746ee0ddc3dd73633
      timeout: 1m
      env:
        - name: GITHUB_APP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-app
              key: client_id
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: github-app
              key: installation_id
        - name: GITHUB_APP_TOKEN_PATH
          value: $(results.token.path)
      script: |
        #!/bin/sh

        gh-utility token \
          --key /secrets/private-key.pem \
          --client-id "${GITHUB_APP_CLIENT_ID}" \
          --installation-id "${GITHUB_APP_INSTALLATION_ID}" \
          --output "${GITHUB_APP_TOKEN_PATH}"
      volumeMounts:
        - name: github-app
          mountPath: /secrets
  volumes:
    - name: github-app
      secret:
        secretName: github-app
