---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/triggers.tekton.dev/eventlistener_v1beta1.json
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cron
  namespace: tekton-ci
spec:
  serviceAccountName: trigger-robot
  triggers:
    - name: renovate
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.pipeline.matches('renovate')"
      bindings:
      - ref: renovate-cron
      template:
        ref: renovate-cron
    - name: link-check
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.pipeline.matches('link-check')"
      bindings:
      - ref: link-check-cron
      template:
        ref: link-check-cron
    - name: publish-schemas
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.pipeline.matches('publish-schemas')"
      template:
        ref: publish-schemas-cron
    - name: update-components
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.pipeline.matches('update-components')"
      template:
        ref: update-components-cron
