---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger-robot
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger-robot-eventlistener
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: trigger-robot
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trigger-robot-eventlistener
subjects:
- kind: ServiceAccount
  name: trigger-robot
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
