---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: containers-renovate
  namespace: tekton-ci
spec:
  schedule: "45 * * * *"
  timezone: "Europe/Berlin"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: quay.io/curl/curl:8.20.0
            args: ["curl", "-X", "POST", "--data", '{"pipeline": "renovate", "repo": "containers"}', "el-cron.tekton-ci.svc.cluster.local:8080"]
          restartPolicy: Never
