---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/triggers.tekton.dev/triggerbinding_v1beta1.json
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: update-components-cron
  namespace: tekton-ci
spec:
  params:
    - name: repo
      value: $(body.repo)
---
# yaml-language-server: $schema=https://kubernetes-schemas.heathcliff.eu/triggers.tekton.dev/triggertemplate_v1beta1.json
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: update-components-cron
  namespace: tekton-ci
spec:
  params:
    - name: repo
      description: The github repository to update.
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: update-components-$(tt.params.repo)-
        namespace: tekton-ci
        labels:
          pipeline: update-components
          repo: $(tt.params.repo)
      spec:
        pipelineRef:
          name: update-components
        params:
          - name: repo
            value: $(tt.params.repo)
        workspaces:
          - name: repo
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: p3-tmp
