---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: minecraft-exporter-link-check
  namespace: tekton-ci
spec:
  schedule: "13 0 * * 0"
  timezone: "Europe/Berlin"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: quay.io/curl/curl:8.21.0
            args: ["curl", "-X", "POST", "--data", '{"pipeline": "link-check", "repo": "minecraft-exporter", "exclude-paths": "vendor"}', "el-cron.tekton-ci.svc.cluster.local:8080"]
          restartPolicy: Never
