---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cerberus-mergeguard/
  - ci/
  - cloudflare-dyndns/
  - containers/
  - cultures-trainer/
  - fleetlock/
  - gh-utility/
  - go-minesweeper/
  - go-wol/
  - godialog/
  - infra/
  - infraspace-savegame-editor/
  - kube-upgrade/
  - minecraft-exporter/
  - pinentry-keyring/
  - predictable-path-provisioner/
  - promremote/
  - simple-fileserver/
  - speedtest-exporter/
  - turbo-clicker/
  - valkey-keepalived/
