---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ci-renovate
  namespace: tekton-ci
spec:
  schedule: "0 * 11 * *"
  timezone: "Europe/Berlin"
  jobTemplate:
    spec:
      # Delete the job after 3 days to free up resources.
      ttlSecondsAfterFinished: 259200
      template:
        spec:
          containers:
          - name: curl
            image: quay.io/curl/curl:8.21.0
            args: ["curl", "-X", "POST", "--data", '{"pipeline": "renovate", "repo": "ci"}', "el-cron.tekton-ci.svc.cluster.local:8080"]
          restartPolicy: Never
