---
name: "Golang lint"

on:
  workflow_call:
    inputs:
      os:
        description: The os used for the runner
        type: string
        required: false
        default: "ubuntu-latest"
      cache:
        description: Persist go-build cache between runs
        type: boolean
        required: false
        default: true
      cmd:
        description: The test command to run
        type: string
        required: false
        default: hack/linter.sh

jobs:
  lint:
    runs-on: "${{ inputs.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Cache
        if: ${{ inputs.cache }}
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            /home/runner/.cache/golangci-lint
            /home/runner/.cache/go-build
          key: golangci-lint

      - name: Run golangci-lint
        run: ${{ inputs.cmd }}
