---
name: Release

on:
  workflow_call:
    inputs:
      draft:
        description: "Create draft release"
        type: boolean
        default: true
      update:
        description: "Update existing release"
        type: boolean
        default: false
      tag:
        description: "Release tag to use"
        type: string
        required: true
      artifacts:
        description: "Artifacts to append, downloads all uploaded artifacts into release/. Takes comma separated list"
        type: string
        required: false
        default: "release/*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: release
          merge-multiple: true

      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          allowUpdates: ${{ inputs.update }}
          artifacts: "${{ inputs.artifacts }}"
          artifactErrorsFailBuild: true
          draft: ${{ inputs.draft }}
          generateReleaseNotes: true
          tag: "${{ inputs.tag }}"
