---
name: Release

on:
  workflow_call:
    inputs:
      draft:
        description: "Create draft release"
        type: boolean
        default: true
      prerelease:
        description: "Mark as prerelease"
        type: boolean
        default: false
      update:
        description: "Update existing release"
        type: boolean
        default: false
      tag:
        description: "Release tag to use"
        type: string
        required: true
      release-artifacts:
        description: "Artifacts to append, downloaded artifacts are found in release/. Takes comma separated list"
        type: string
        required: false
        default: "release/*"
      artifacts:
        description: "Artifacts to download. Artifacts will be downloaded into release/"
        type: string
        required: false
        default: "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: release
          pattern: "${{ inputs.artifacts }}"
          merge-multiple: true


      - uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          allowUpdates: ${{ inputs.update }}
          artifacts: "${{ inputs.release-artifacts }}"
          artifactErrorsFailBuild: true
          draft: ${{ inputs.draft }}
          generateReleaseNotes: true
          tag: "${{ inputs.tag }}"
          prerelease: ${{ inputs.prerelease }}
