---
name: "Publish Schemas"

on:
  workflow_call:

jobs:
  publish-manifests:
    runs-on: ["arc-${{ github.event.repository.name }}"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Flux
        uses: fluxcd/flux2/action@5c5c15ea212b8f029a110f9975851d25c8272695 # v2.2.2

      - name: Setup kubectl
        run: |
          set -e
          arch="$(uname -m)"
          case "${arch}" in
            aarch64)
              arch="arm64"
              ;;
            x86_64)
              arch="amd64"
              ;;
            *)
          esac
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${arch}/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Setup Python
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-yaml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup crd-extractor
        run: |
          curl -SL -o $GITHUB_WORKSPACE/crd-extractor.sh https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/Utilities/crd-extractor.sh
          chmod 755 $GITHUB_WORKSPACE/crd-extractor.sh

      - name: Write kubeconfig
        id: kubeconfig
        uses: timheuer/base64-to-file@adaa40c0c581f276132199d4cf60afa07ce60eac # v1.2
        with:
          encodedString: ${{ secrets.KUBECONFIG }}
          fileName: kubeconfig

      - name: Run crd-extractor
        env:
          KUBECONFIG: ${{ steps.kubeconfig.outputs.filePath }}
        shell: bash
        run: |
          bash $GITHUB_WORKSPACE/crd-extractor.sh

      - name: Publish manifests
        shell: bash
        run: |
          flux push artifact oci://ghcr.io/${{ github.repository_owner }}/manifests/kubernetes-schemas:${{ github.event.repository.name }} \
              --path="/home/runner/.datree/crdSchemas" \
              --source="${{ github.repositoryUrl }}" \
              --revision="${{ github.ref_name }}@sha1:$(git rev-parse HEAD)"
