name: "Kubernetes update-components"

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1.10.2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Flux
        uses: fluxcd/flux2/action@896e0fa46d5107a05e953dd0a5261d78a145ec8c # v2.3.0

      - name: Check for updates
        run: |
          make update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
            token: "${{ steps.app-token.outputs.token }}"
            branch: update-components
            committer: bot-ahsoka[bot] <bot-ahsoka[bot]@users.noreply.github.com>
            author: bot-ahsoka[bot] <bot-ahsoka[bot]@users.noreply.github.com>
            commit-message: |
              Update components to latest version

              Created via `make update`

            signoff: true
            title: "Update components to latest version"
            body: |
              Created via `make update`
            labels: update,flux
