---
name: "Kubernetes flux diff"

on:
  workflow_call:

jobs:
  flux-diff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ["kubernetes/pi-cluster", "kubernetes/remote-ops"]
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup Flux
        uses: fluxcd/flux2/action@534684601ec8888beb0cc4f51117b59e97606c4d # v2.2.3

      - name: Checkout PR branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: pr
          token: "${{ steps.app-token.outputs.token }}"

      - name: Checkout live branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: main
          path: live
          token: "${{ steps.app-token.outputs.token }}"

      - name: Prepare files for CI
        run: |
          set -e
          pr/hack/prepare-flux-files-for-ci.sh
          live/hack/prepare-flux-files-for-ci.sh

      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@e630daec1a1bcd24dc80f5100c6e1c7b6a091153 # 4.3.1
        id: diff
        with:
          path: "${{ matrix.path }}"
          resource: "${{ matrix.resource }}"
          token: "${{ steps.app-token.outputs.token }}"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
