---
name: "Kubernetes Kubeconform"

on:
  workflow_call:

env:
  KUBERNETES_DIR: ./kubernetes
  SCHEMA_DIR: /home/runner/.datree/crdSchemas

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Tools
        shell: bash
        run: brew install fluxcd/tap/flux kubeconform kustomize

      - name: Download script
        run: curl -SLO https://raw.githubusercontent.com/heathcliff26/ci/main/scripts/kubeconform.sh && chmod +x kubeconform.sh

      - name: Download CRDs
        shell: bash
        run: |
          mkdir -p ${{ env.SCHEMA_DIR }}
          flux pull artifact oci://ghcr.io/${{ github.repository_owner }}/manifests/kubernetes-schemas:latest \
              --output=${{ env.SCHEMA_DIR }}

      - name: Run kubeconform
        shell: bash
        run: bash ./kubeconform.sh ${{ env.KUBERNETES_DIR }} ${{ env.SCHEMA_DIR }}
