name: "Update flux"

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f04aa94d10cf56334d1c580e077ce2e3569e805d # v1.6.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Flux
        uses: fluxcd/flux2/action@5c5c15ea212b8f029a110f9975851d25c8272695 # v2.2.2

      - name: Check for updates
        id: update
        run: |
          flux install --export > ./kubernetes/flux-system/gotk-components.yaml

          VERSION="$(flux -v)"
          echo "flux_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
            token: "${{ steps.app-token.outputs.token }}"
            branch: update-flux
            commit-message: |
              Flux: Update to ${{ steps.update.outputs.flux_version }}

              Signed-off-by: bot-ahsoka <noreply@heathcliff.eu>
            title: "Flux: Update to ${{ steps.update.outputs.flux_version }}"
            body: |
              ${{ steps.update.outputs.flux_version }}
            labels: flux
