name: "Kubernetes update-components"

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bf627a5a4415baceb13b8feb7cdbe1f4b112dc8d # v1.8.2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Flux
        uses: fluxcd/flux2/action@534684601ec8888beb0cc4f51117b59e97606c4d # v2.2.3

      - name: Check for updates
        run: |
          make update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@a4f52f8033a6168103c2538976c07b467e8163bc # v6.0.1
        with:
            token: "${{ steps.app-token.outputs.token }}"
            branch: update-components
            committer: bot-ahsoka[bot] <bot-ahsoka[bot]@users.noreply.github.com>
            author: bot-ahsoka[bot] <bot-ahsoka[bot]@users.noreply.github.com>
            commit-message: |
              Update components to latest version

              Created via `make update`

            signoff: true
            title: "Update components to latest version"
            body: |
              Created via `make update`
            labels: update,flux
