---
name: "Kubernetes flux diff"

on:
  workflow_call:

jobs:
  flux-diff:
    runs-on: arc-remote-ops
    strategy:
      matrix:
        path: ["kubernetes/home-ops", "kubernetes/remote-ops"]
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@b2a302b9a642580cae998e6ba2076ffd28e61317 # master

      - name: Setup Tools
        shell: bash
        run: brew install helm kubeconform kustomize

      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@d4ebcae7ae08c8c8b8b7c1f515cf86759f9ca950 # 8.1.0
        id: diff
        with:
          path: "${{ matrix.path }}"
          resource: "${{ matrix.resource }}"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@ffd016c7e151d97d69d21a843022fd4cd5b96fe5 # v3.9.0
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
