---
name: "Validate Renovate Config"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main"]
    paths:
      - .github/renovate.json5
  pull_request:
    branches: ["main"]
    paths:
      - .github/renovate.json5
      - .github/workflows/renovate-config-validator.yaml

env:
  RENOVATE_BOT_CONFIG_FILE: .github/renovate-bot.json5
  RENOVATE_REPO_CONFIG_FILE: .github/renovate.json5

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate bot config
        if: ${{ hashFiles(env.RENOVATE_BOT_CONFIG_FILE) != '' }}
        uses: docker://renovate/renovate:43.220.0
        with:
          args: renovate-config-validator --strict "${{ env.RENOVATE_BOT_CONFIG_FILE }}"

      - name: Validate repository
        uses: docker://renovate/renovate:43.220.0
        with:
          args: renovate-config-validator --strict "${{ env.RENOVATE_REPO_CONFIG_FILE }}"
