---
name: Trigger Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Make no changes
        default: "false"
        required: false
      logLevel:
        description: Set log-level
        default: debug
        required: false
  schedule:
    - cron: "10 * * * 5"
  push:
    branches: ["main"]
    paths:
      - .github/renovate-bot.json5
      - .github/renovate.json5
      - .github/renovate/**.json5

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      dry-run: ${{ steps.config.outputs.dry-run }}
      log-level: "${{ steps.config.outputs.log-level }}"
    steps:
      - name: Generate config from dispatch variables or defaults
        id: config
        run: |
          echo "dry-run=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN }}" >> "$GITHUB_OUTPUT"
          echo "log-level=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "$GITHUB_OUTPUT"

  renovate:
    needs: prepare
    uses: heathcliff26/ci/.github/workflows/renovate.yaml@main
    with:
      dry-run: ${{ needs.prepare.outputs.dry-run }}
      log-level: "${{ needs.prepare.outputs.log-level }}"
    secrets: inherit
